# Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Layouts
Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpacingAroundOperators:
  Enabled: false

# Styles
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false
