# Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Layouts
Layout/ExtraSpacing:
  Enabled: false

Layout/HashAlignment:
  Exclude:
  - 'Guardfile'

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Styles
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
  - 'bin/*'

# Lint
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Naming
Naming/BinaryOperatorParameterName:
  Enabled: false
